

import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavWrapper from "./components/reuseable/reusable-home/NavWrapper";
import { Analytics } from "@vercel/analytics/next"
import { Plus } from "lucide-react";
import Link from "next/link";
// import { usePathname } from "next/navigation";
import AddPostbutton from "./components/reuseable/reusable-home/AddPostbutton";





export const metadata: Metadata = {
  title: "Emerge Literature Club | YCCE",
  description: "Generated by create next app",
  icons:{
    icon:'/image/logo.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

// const pathname = usePathname();
 
  return (
    <html lang="en">
      <body
        className={` antialiased`}
         suppressHydrationWarning={true}
      >

        <Analytics/>
        <AddPostbutton/>
     
        <NavWrapper>{children}</NavWrapper>
    
      </body>
    </html>
  );
}
