
import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./components/reuseable/reusable-home/nav";




export const metadata: Metadata = {
  title: "Emerge Literature Club | YCCE",
  description: "Generated by create next app",
  icons:{
    icon:'/image/logo.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <html lang="en">
      <body
        className={` antialiased`}
         suppressHydrationWarning={true}
      >
     <Nav/>
        {children}
      </body>
    </html>
  );
}
